language: java
services:
- docker
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./scripts/docker_push.sh && bash ./scripts/terraform_apply.sh
  on:
    branch: master
docker:
  username:
    secure: jF+k6So2rqaQ0mP3JZAoX3yHjTbrAq4/6kZ2Q75x5a+1z5J0juu+iifrcZipTUHf/AlXNEOGOOdWkRGThT8GalKxdLOgWb4L9KNc2Nikjg1alT/Qf2JMIZJxyKihNSPHT1XgD6rDpR6rtGF99hESRw9NiU3pLuZllC2UmmpuRLofJL09+hdsLeoznpCWhDQjYFkzVh5dkN2wbNwYRyIBYTzsBvcrTB/22lsAbm0gNDiPJfOrQ+tuHYN81zF7+llUV0jpllpa2tGFhl5mGA6cPyMff6z8BiMb84eR5gM17sHGQ1EHR3JtLONA0pXrMNPHf1N/Y5qYWVIvlqFnV2DVPL5CgUTkpBewP5F/1Y9ei5D2hUfzOuA9acuWw8lCmDG3v639Uy//P112dIjmcltOK42i/W5aFlvxuB4PXgi/IJuoQEWY0v373pGLhvAts9+OY2gKpPpHklxx6yttNWftbXPXzzisdJblFSt4RJwr0ojpGSwg+j8yBYivZ0N25XBfiJt2WVhWOQ1W0RH+yckmEEWZmzQolNIuSBTxnyO/hIUNzSiOuhYfb93KF71J+CytVsgocigtU1JqtO/qmS7sIkwaIxfmjfFVsZlRZk/r7AWGr0cby5kHIwk0XrGjG6/Hzv12z5nAUVzVj2Pg2rik6n4Dl+adLQRhiOHMETH0U2A=
  password:
    secure: ChIbb+Qyxt4XN3nSA7Kh/GId5PezNp50EcbAtVeuCWBAy/kksMCMY+0RbYFMC2yGHx+vDyEUc8TL0qliItlhnMfDrlzKTgVO6iQjR0wduPZGhXU2Mct0SYXKtWHuXHl2KaEtZjc4h+yg2zFdRAC6r1obyPLaZ96IMXJmpcxdj2WB2+ieXvQjw4lKflG/RrUDbc8Oxu9H1sdfWUospjjnBG7ZJHtm6FnN+yP4Cv4GU2E4ZpX5JnIU6fHfu3zP522uBfzZ58m9NJprK10Qpw/wkROmi/3yvK7T/h42WTUxrFWqzqZAz8M4SmHaLSWVZLNE5DGWgwM9d4ZePSdjiyAVx5frEFdQz8tVgikeVAEBYk7XLLOjQ9pJGXcBm3YWU2OHm+Npq9OyvVCf9AoL4lXNTgJVFMuQjEsZj3wV3PukY0d0SQz8qIjcOlHNtsYYnDzQOhxQk7qsFPh1sAv2xy2PmcHjHmGg+rlpZxO1gm16c16tPkhmIduMKStaywUpUfVb7y0qnHLyBvyBR73hs6Kzsnvf4TO4P0ujQEG5+hiW0qFDTtusfdWtBBINwZuEPsdEGsG/lLxh0R3TYbjWJkryf1itdSXgc7TlbQ0dQ1b19Iq1+rH+pwGErsMXoMRNLoqmVBetz6ajd4cuODs3KFLSsDoB41ga1qsPsCIPOs8IE7E=
