version: '3.3'

services:
  api:
    build:
      context: ./api
    image: olaven/trees-api
  frontend:
    build:
      context: ./frontend
    image: olaven/trees-frontend
  discovery:
    build:
      context: ./discovery
    image: olaven/trees-discovery
  gateway:
    build:
      context: ./gateway
    ports:
          - "80:8080"
