version: '3.3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9001:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9002:80"
