version: '3.3'

services:
  # Service registery
  registery:
    build:
      context: ./registery
    image: olaven/trees-registery
    ports:
      - "8080:8761" # TODO: remove mapping
  gateway:
    build:
      context: ./gateway
    image: olaven/trees-gateway
    depends_on:
      - registery
    ports:
        - "80:8080"
  api:
    build:
      context: ./api
    image: olaven/trees-api
    depends_on:
      - gateway
  frontend:
    build:
      context: ./frontend
    image: olaven/trees-frontend
    depends_on:
      - gateway
