version: '3.3'

services:
  # Service registery
  registry:
    build:
      context: ./registry
    #image: olaven/trees-registry
  gateway:
    build:
      context: ./gateway
    #image: olaven/trees-gateway
    depends_on:
      - registry
    ports:
        - "80:8080"
  api:
    build:
      context: ./api
    #image: olaven/trees-api
    depends_on:
      - gateway

  frontend:
    build:
      context: ./frontend
    #image: olaven/trees-frontend
    depends_on:
      - gateway
