#server.servlet.context-path=/api - removed as is only applicable to API, not entire application
server:
  port: ${PORT:8080}
togglz:
  features:
    INFO_PAGE:
      enabled: true
spring:
  application:
    name: api
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true # this is false in Andrea's example. That ruins frontend..
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

