#server.servlet.context-path=/api - removed as is only applicable to API, not entire application
server:
  port: ${PORT:8080}
spring:
  application:
    name: api
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  datasource:
    url: "jdbc:postgresql://postgres_api:5432/test"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect #TODO: perhaps I need a postgis-image in prod/compose
    hibernate:
      ddl-auto: create-drop # TODO: validate with flyway or similar
eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
